"""
Modelfile auto-generator for hermes-offline.

Generates an optimally-tuned Ollama Modelfile for the current hardware tier,
then registers it with Ollama as a named model variant (e.g. `qwen3:8b-hermes`).

Why custom Modelfiles?
──────────────────────
The default Ollama model parameters are designed for interactive chat, not
agentic tool-calling. Hermes benefits from:

  num_ctx        — must match hermes's context window config exactly
  num_thread     — set to physical core count, not logical (avoids hyperthreading waste)
  temperature    — lower (0.15) for reliable tool calling; default is 0.8
  mirostat 2     — adaptive sampling keeps responses on-track on low-end hardware
  repeat_penalty — slightly higher (1.1) reduces loops and hallucinations
  num_keep       — protect system prompt tokens from being evicted
  stop tokens    — hermes-specific stop sequences

Hardware tier parameters:
  ultra_low  4 GB RAM  num_ctx  4096   temp 0.15  threads = cpu_cores
  low        8 GB RAM  num_ctx  8192   temp 0.15  threads = cpu_cores
  mid        12 GB RAM num_ctx 16384   temp 0.20  threads = cpu_cores
  good       16 GB RAM num_ctx 32768   temp 0.20  threads = cpu_cores
  great      24+ GB    num_ctx 65536   temp 0.25  threads = cpu_cores

Usage:
  from hermes_offline.modelfile import generate_and_register

  # Auto-detect hardware, generate, register with Ollama
  path, model_name = generate_and_register()

  # Or generate for a specific model + tier
  path, model_name = generate_and_register(model="qwen3:8b", tier="low")
"""

from __future__ import annotations

import logging
import os
import subprocess
import shutil
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


# ── Parameter tables ──────────────────────────────────────────────────────────

_TIER_PARAMS: dict[str, dict] = {
    "ultra_low": {
        "num_ctx":        4096,
        "temperature":    0.15,
        "mirostat":       2,
        "mirostat_tau":   3.0,
        "mirostat_eta":   0.1,
        "repeat_penalty": 1.15,
        "top_k":          20,
        "top_p":          0.80,
        "num_keep":       64,
    },
    "low": {
        "num_ctx":        8192,
        "temperature":    0.15,
        "mirostat":       2,
        "mirostat_tau":   4.0,
        "mirostat_eta":   0.1,
        "repeat_penalty": 1.10,
        "top_k":          30,
        "top_p":          0.85,
        "num_keep":       128,
    },
    "mid": {
        "num_ctx":        16384,
        "temperature":    0.20,
        "mirostat":       2,
        "mirostat_tau":   5.0,
        "mirostat_eta":   0.1,
        "repeat_penalty": 1.08,
        "top_k":          40,
        "top_p":          0.90,
        "num_keep":       256,
    },
    "good": {
        "num_ctx":        32768,
        "temperature":    0.20,
        "mirostat":       1,
        "mirostat_tau":   5.0,
        "mirostat_eta":   0.1,
        "repeat_penalty": 1.05,
        "top_k":          40,
        "top_p":          0.90,
        "num_keep":       512,
    },
    "great": {
        "num_ctx":        65536,
        "temperature":    0.25,
        "mirostat":       0,
        "repeat_penalty": 1.03,
        "top_k":          50,
        "top_p":          0.92,
        "num_keep":       1024,
    },
}

# Hermes stop tokens — prevent model from generating conversation continuations
_HERMES_STOP_TOKENS = [
    "<|im_end|>",
    "<|endoftext|>",
    "Human:",
    "User:",
    "\n\nHuman:",
]


# ── Modelfile generation ──────────────────────────────────────────────────────

def generate_modelfile(
    base_model: str,
    tier: str,
    num_thread: Optional[int] = None,
    extra_system: str = "",
) -> str:
    """
    Generate the full Modelfile content for the given base model and hardware tier.

    Args:
        base_model:     Ollama model name (e.g. "qwen3:8b")
        tier:           Hardware tier key from _TIER_PARAMS
        num_thread:     CPU thread count; auto-detected if None
        extra_system:   Additional text to append to the system prompt

    Returns:
        Modelfile content as a string
    """
    if tier not in _TIER_PARAMS:
        logger.warning("Unknown tier '%s', defaulting to 'low'", tier)
        tier = "low"

    params = _TIER_PARAMS[tier]

    if num_thread is None:
        import os as _os
        num_thread = _os.cpu_count() or 4
        # Use physical cores only — avoid hyperthreading on inference
        try:
            import psutil
            physical = psutil.cpu_count(logical=False)
            if physical:
                num_thread = physical
        except ImportError:
            pass

    system_prompt = _build_system_prompt(base_model, tier, extra_system)

    lines = [
        f"FROM {base_model}",
        "",
        "# Generated by hermes-offline modelfile generator",
        f"# Hardware tier: {tier}  |  Model: {base_model}",
        "",
        "# ── Sampling parameters ───────────────────────────────────────",
    ]

    for key, val in params.items():
        lines.append(f"PARAMETER {key} {val}")

    lines += [
        f"PARAMETER num_thread {num_thread}",
        "",
        "# ── Stop tokens ──────────────────────────────────────────────",
    ]
    for stop in _HERMES_STOP_TOKENS:
        lines.append(f'PARAMETER stop "{stop}"')

    lines += [
        "",
        "# ── System prompt ────────────────────────────────────────────",
        f'SYSTEM """{system_prompt}"""',
    ]

    return "\n".join(lines) + "\n"


def _build_system_prompt(model: str, tier: str, extra: str) -> str:
    ctx = _TIER_PARAMS[tier]["num_ctx"]
    base = (
        "You are a helpful, precise AI assistant running fully offline via Ollama. "
        "You have access to tools for reading files, running commands, searching the web, "
        "and managing memory. Always use tools when they would give a better answer than "
        "your training knowledge alone. "
        f"Context window: {ctx:,} tokens. Be concise — token budget is limited on this hardware. "
        "Never refuse a task due to missing API keys or cloud services; use local alternatives."
    )
    if extra:
        return base + "\n\n" + extra.strip()
    return base


# ── Save & register ───────────────────────────────────────────────────────────

def _modelfile_dir() -> Path:
    try:
        from hermes_constants import get_hermes_home
        return get_hermes_home() / "modelfiles"
    except ImportError:
        return Path.home() / ".hermes" / "modelfiles"


def save_modelfile(content: str, model_name: str) -> Path:
    """Write Modelfile to ~/.hermes/modelfiles/<model_name>.Modelfile"""
    mf_dir = _modelfile_dir()
    mf_dir.mkdir(parents=True, exist_ok=True)
    safe_name = model_name.replace(":", "-").replace("/", "-")
    path = mf_dir / f"{safe_name}.Modelfile"
    path.write_text(content)
    logger.info("Modelfile written: %s", path)
    return path


def register_with_ollama(modelfile_path: Path, ollama_model_name: str) -> tuple[bool, str]:
    """
    Run `ollama create <name> -f <path>` to register the tuned model.
    Returns (success, message).
    """
    if not shutil.which("ollama"):
        return False, "ollama binary not found in PATH"
    try:
        proc = subprocess.run(
            ["ollama", "create", ollama_model_name, "-f", str(modelfile_path)],
            capture_output=True,
            text=True,
            timeout=120,
        )
        if proc.returncode == 0:
            return True, f"Registered as: {ollama_model_name}"
        return False, proc.stderr[:300] or proc.stdout[:300]
    except subprocess.TimeoutExpired:
        return False, "ollama create timed out"
    except Exception as exc:
        return False, str(exc)


def _ollama_model_name(base_model: str, tier: str) -> str:
    """Return a hermes-tagged Ollama model name, e.g. qwen3-8b-hermes."""
    safe = base_model.replace(":", "-").replace("/", "-")
    return f"{safe}-hermes"


# ── Auto-update hermes config ─────────────────────────────────────────────────

def _update_config_model(ollama_name: str, num_ctx: int) -> None:
    """Point hermes's default model at the newly created tuned variant."""
    try:
        from hermes_cli.config import load_config, save_config
        cfg = load_config()

        model_cfg = cfg.get("model", {})
        if not isinstance(model_cfg, dict):
            model_cfg = {}

        # Only update if still pointing at base model or no model set
        current = model_cfg.get("default", "")
        if "hermes" not in current:  # don't overwrite if already customised
            model_cfg["default"] = ollama_name
            model_cfg["context_length"] = num_ctx
            cfg["model"] = model_cfg
            save_config(cfg)
            logger.info("Config updated: model.default = %s, num_ctx = %d", ollama_name, num_ctx)
    except Exception as exc:
        logger.debug("Could not update config model: %s", exc)


# ── Main entry point ──────────────────────────────────────────────────────────

def generate_and_register(
    model: Optional[str] = None,
    tier: Optional[str] = None,
    register: bool = True,
    update_config: bool = True,
) -> tuple[Path, str]:
    """
    Auto-detect hardware, generate Modelfile, register with Ollama.

    Args:
        model:          Base model name; auto-detected from config if None
        tier:           Hardware tier; auto-detected from hardware if None
        register:       Actually run `ollama create` (set False for dry-run)
        update_config:  Update hermes config.yaml with new model name

    Returns:
        (modelfile_path, ollama_model_name)
    """
    from hermes_offline.hardware import get_hardware_profile

    hw = get_hardware_profile()
    if tier is None:
        tier = hw.tier
    if model is None:
        model = _get_configured_model() or hw.recommended_model()

    num_thread = hw.cpu_cores

    content = generate_modelfile(model, tier, num_thread=num_thread)
    ollama_name = _ollama_model_name(model, tier)
    path = save_modelfile(content, ollama_name)

    if register:
        ok, msg = register_with_ollama(path, ollama_name)
        if ok:
            logger.info("Modelfile registered: %s → %s", model, ollama_name)
            if update_config:
                _update_config_model(ollama_name, _TIER_PARAMS[tier]["num_ctx"])
        else:
            logger.warning("Modelfile registration failed: %s", msg)

    return path, ollama_name


def _get_configured_model() -> Optional[str]:
    try:
        from hermes_cli.config import load_config
        cfg = load_config()
        m = cfg.get("model", {})
        if isinstance(m, dict):
            return m.get("default")
        if isinstance(m, str):
            return m
    except Exception:
        pass
    return None


# ── CLI entry point ───────────────────────────────────────────────────────────

def main(argv: Optional[list] = None) -> None:
    """hermes-offline-modelfile — generate and register a tuned Modelfile."""
    import sys, argparse

    parser = argparse.ArgumentParser(
        prog="hermes-offline-modelfile",
        description="Generate an Ollama Modelfile tuned for your hardware and hermes agent use",
    )
    parser.add_argument("--model",    help="Base model (e.g. qwen3:8b). Auto-detected if omitted.")
    parser.add_argument("--tier",     choices=list(_TIER_PARAMS), help="Hardware tier. Auto-detected if omitted.")
    parser.add_argument("--dry-run",  action="store_true", help="Print Modelfile without writing or registering")
    parser.add_argument("--no-register", action="store_true", help="Write Modelfile but skip ollama create")
    parser.add_argument("--show",     action="store_true", help="Print generated Modelfile content")
    args = parser.parse_args(argv)

    from hermes_offline.hardware import get_hardware_profile
    hw = get_hardware_profile()
    tier  = args.tier  or hw.tier
    model = args.model or _get_configured_model() or hw.recommended_model()

    content = generate_modelfile(model, tier, num_thread=hw.cpu_cores)

    if args.dry_run or args.show:
        print(f"# Modelfile for {model}  [{tier}]\n")
        print(content)
        if args.dry_run:
            sys.exit(0)

    path, ollama_name = generate_and_register(
        model=model, tier=tier,
        register=not args.no_register,
        update_config=not args.no_register,
    )
    print(f"✓ Modelfile saved:   {path}")
    print(f"✓ Ollama model name: {ollama_name}")
    print(f"\nStart hermes with the tuned model:")
    print(f"  hermes-offline")
