"""
Offline-first interactive setup wizard for Hermes Agent.

This wizard replaces the default hermes setup for offline use:
  1. Detect hardware (RAM, VRAM, CPU)
  2. Check if Ollama is running; offer to install it
  3. List installed models; recommend the best for detected hardware
  4. Offer to pull the recommended model
  5. Write ~/.hermes/config.yaml with offline-first defaults
  6. Optional: setup gateway (Telegram, Discord, etc.)
  7. Optional: install piper-tts for local voice
  8. Optional: install faster-whisper for local transcription

Run standalone:
    python -m hermes_offline.setup
Or via entry point:
    hermes-offline-setup
"""

from __future__ import annotations

import json
import os
import platform
import subprocess
import sys
import urllib.request
from pathlib import Path
from typing import Optional

try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Confirm, Prompt
    from rich.table import Table
    console = Console()
except ImportError:
    # Minimal fallback without rich
    class Console:
        def print(self, *args, **kwargs): print(*args)
        def rule(self, *args, **kwargs): print("─" * 60)
    class Panel:
        def __new__(cls, content, **kwargs): return content
    class Confirm:
        @staticmethod
        def ask(q, default=True): 
            ans = input(f"{q} [{'Y/n' if default else 'y/N'}]: ").strip().lower()
            return (ans in ("y", "yes", "")) if default else (ans in ("y", "yes"))
    class Prompt:
        @staticmethod
        def ask(q, default=""): return input(f"{q} [{default}]: ").strip() or default
    console = Console()


def _default_hermes_home() -> Path:
    """Platform-aware default Hermes home directory."""
    env = os.environ.get("HERMES_HOME", "").strip()
    if env:
        return Path(env)
    if os.name == "nt":  # Windows
        local = os.environ.get("LOCALAPPDATA", "").strip()
        base = Path(local) if local else Path.home() / "AppData" / "Local"
        return base / "hermes"
    return Path.home() / ".hermes"

HERMES_HOME = _default_hermes_home()

OFFLINE_CONFIG_TEMPLATE = """\
# Hermes Agent — Offline-First Configuration
# Generated by hermes-offline setup wizard
# Edit at any time: hermes config edit

# ── Provider ──────────────────────────────────────────────
provider: ollama-local
model:
  default: {model}
endpoint: http://127.0.0.1:11434/v1
api_key: ollama
stream: true

# ── Context management (tuned for local LLMs) ─────────────
context:
  compression_threshold: 0.70
  max_tool_output_chars: {max_tool_chars}
  summary_on_compress: true

# ── Web search (no API key required) ──────────────────────
web:
  backend: duckduckgo
  # Set to searxng if you run a local SearXNG instance
  # searxng_url: http://localhost:8080

# ── TTS (local — no key required) ─────────────────────────
tts:
  provider: {tts_provider}
  voice: en_US-lessac-medium

# ── Memory ────────────────────────────────────────────────
memory:
  backend: sqlite_fts5

# ── Self-evolution (lightweight mode for local LLMs) ──────
evolution:
  mode: lightweight
  population_size: 2

# ── Ollama performance tuning ─────────────────────────────
ollama_options:
  num_ctx: {num_ctx}
  temperature: 0.2
  repeat_penalty: 1.1
  num_predict: 2048
"""


def main(argv: list[str] | None = None) -> None:
    import argparse
    parser = argparse.ArgumentParser(
        prog="hermes-offline-setup",
        description="Interactive setup wizard for Hermes Offline (installs Ollama, selects model, writes config).",
    )
    parser.parse_args(argv)  # handles --help; wizard takes no CLI flags
    console.print()
    console.print(Panel(
        "[bold cyan]Hermes Agent — Offline Setup Wizard[/bold cyan]\n"
        "[dim]Zero API keys · Zero subscriptions · Runs entirely on your machine[/dim]",
        expand=False,
    ))
    console.print()

    # 1. Detect hardware
    console.rule("[bold]Step 1: Hardware Detection[/bold]")
    hw = _detect_hardware()
    console.print(hw["summary"])
    console.print()

    # 2. Check / install Ollama
    console.rule("[bold]Step 2: Ollama[/bold]")
    models = _check_ollama()

    # 3. Model selection
    console.rule("[bold]Step 3: Model Selection[/bold]")
    model = _select_model(models, hw)

    # 4. TTS
    console.rule("[bold]Step 4: Local TTS (optional)[/bold]")
    tts_provider = _setup_tts()

    # 5. Write config
    console.rule("[bold]Step 5: Writing Configuration[/bold]")
    _write_config(model, hw, tts_provider)

    # 6. Done
    console.rule()
    console.print()
    console.print("[bold green]✓ Setup complete![/bold green]")
    console.print()
    console.print("Run Hermes with:")
    console.print("  [bold cyan]hermes[/bold cyan]               — start interactive session")
    console.print("  [bold cyan]hermes --tui[/bold cyan]         — launch TUI")
    console.print("  [bold cyan]hermes model[/bold cyan]         — switch model")
    console.print()


def _detect_hardware() -> dict:
    try:
        from hermes_offline.hardware import get_hardware_profile
        hw = get_hardware_profile()
        return {
            "tier": hw.tier,
            "recommended_model": hw.recommended_model(),
            "recommended_ctx": hw.recommended_ctx(),
            "summary": hw.summary(),
            "available_ram_gb": hw.available_ram_gb,
        }
    except Exception as exc:
        console.print(f"[yellow]Hardware detection failed: {exc}[/yellow]")
        return {
            "tier": "mid",
            "recommended_model": "qwen3:4b",
            "recommended_ctx": 8192,
            "summary": "  Could not detect hardware — using safe defaults",
            "available_ram_gb": 8.0,
        }


def _check_ollama() -> list[str]:
    console.print("Checking for local Ollama instance...")
    try:
        with urllib.request.urlopen("http://127.0.0.1:11434/api/tags", timeout=3) as r:
            data = json.loads(r.read())
            models = [m["name"] for m in data.get("models", [])]
            console.print(f"[green]✓ Ollama is running[/green] ({len(models)} models installed)")
            if models:
                console.print("  Installed: " + ", ".join(models[:6]))
            return models
    except Exception:
        console.print("[yellow]Ollama not running or not installed.[/yellow]")

    if Confirm.ask("Install Ollama now?", default=True):
        _install_ollama()
        return _check_ollama()

    return []


def _install_ollama() -> None:
    system = platform.system()
    console.print(f"\n[bold]Installing Ollama on {system}...[/bold]")

    if system in ("Linux", "Darwin"):
        console.print("Running: curl -fsSL https://ollama.com/install.sh | sh")
        try:
            subprocess.run(
                "curl -fsSL https://ollama.com/install.sh | sh",
                shell=True,
                check=True,
            )
            console.print("[green]✓ Ollama installed[/green]")
        except subprocess.CalledProcessError as exc:
            console.print(f"[red]Installation failed: {exc}[/red]")
            console.print("Install manually: https://ollama.com/download")
    elif system == "Windows":
        console.print("Please download the Ollama installer from: https://ollama.com/download/windows")
    else:
        console.print("Please install Ollama from: https://ollama.com/download")


def _select_model(installed_models: list[str], hw: dict) -> str:
    recommended = hw["recommended_model"]

    if installed_models:
        # Find best installed model for this hardware tier
        try:
            from hermes_offline.providers import detect_best_installed_model
            best = detect_best_installed_model(installed_models, hw["tier"])
            if best:
                console.print(f"[green]Best installed model for your hardware: {best}[/green]")
                if Confirm.ask(f"Use {best}?", default=True):
                    return best
        except Exception:
            pass

    console.print(f"\nRecommended model for your hardware: [bold cyan]{recommended}[/bold cyan]")
    ctx_gb = hw.get("recommended_ctx", 8192) / 1024

    try:
        size_info = _get_model_size(recommended)
        console.print(f"  Download size: ~{size_info}")
    except Exception:
        pass

    if not installed_models or Confirm.ask(f"Pull {recommended} now?", default=True):
        if _pull_model(recommended):
            return recommended

    # Let user pick manually
    if installed_models:
        console.print("\nInstalled models:")
        for i, m in enumerate(installed_models, 1):
            console.print(f"  {i}. {m}")
        choice = Prompt.ask("Enter model name or number", default=installed_models[0])
        if choice.isdigit():
            idx = int(choice) - 1
            if 0 <= idx < len(installed_models):
                return installed_models[idx]
        return choice

    custom = Prompt.ask("Enter model name to use", default=recommended)
    return custom


def _get_model_size(model: str) -> str:
    sizes = {
        "qwen3:1.7b": "1.1 GB", "qwen3:4b": "2.6 GB", "qwen3:8b": "5.2 GB",
        "qwen3:14b": "9.3 GB", "qwen3-coder:30b": "19 GB",
        "llama3.1:8b": "4.7 GB", "phi4-mini": "2.5 GB",
        "qwen2.5-coder:14b": "9.0 GB", "nomic-embed-text": "274 MB",
    }
    family = model.split(":")[0].lower()
    return sizes.get(model, sizes.get(family, "unknown size"))


def _pull_model(model: str) -> bool:
    console.print(f"\n[bold]Pulling {model}...[/bold]")
    try:
        result = subprocess.run(
            ["ollama", "pull", model],
            check=True,
        )
        console.print(f"[green]✓ {model} ready[/green]")
        return True
    except subprocess.CalledProcessError as exc:
        console.print(f"[red]Pull failed: {exc}[/red]")
        return False
    except FileNotFoundError:
        console.print("[red]'ollama' not found in PATH. Is Ollama installed?[/red]")
        return False


def _setup_tts() -> str:
    import shutil
    if shutil.which("piper"):
        console.print("[green]✓ piper-tts found — using as default TTS[/green]")
        return "piper"

    try:
        import piper  # noqa: F401
        console.print("[green]✓ piper-tts (Python) found[/green]")
        return "piper"
    except ImportError:
        pass

    console.print("Local TTS not detected. Options:")
    console.print("  1. piper-tts (recommended, fast, MIT license)")
    console.print("  2. edge-tts (Microsoft Edge voices, needs internet)")
    console.print("  3. Skip (no TTS)")

    choice = Prompt.ask("Choose TTS provider", default="2")
    if choice == "1":
        console.print("Install piper: pip install piper-tts")
        console.print("Then re-run this wizard.")
        return "piper"
    elif choice == "2":
        return "edge"
    return "none"


def _write_config(model: str, hw: dict, tts_provider: str) -> None:
    HERMES_HOME.mkdir(parents=True, exist_ok=True)
    config_path = HERMES_HOME / "config.yaml"

    max_tool_chars = 2000 if hw["tier"] in ("ultra_low", "low") else 3000
    num_ctx = hw.get("recommended_ctx", 8192)

    config_content = OFFLINE_CONFIG_TEMPLATE.format(
        model=model,
        max_tool_chars=max_tool_chars,
        tts_provider=tts_provider,
        num_ctx=num_ctx,
    )

    if config_path.exists():
        backup = config_path.with_suffix(".yaml.bak")
        config_path.rename(backup)
        console.print(f"[dim]Existing config backed up to {backup}[/dim]")

    config_path.write_text(config_content)
    console.print(f"[green]✓ Config written to {config_path}[/green]")

    # Also write .env with Ollama settings
    env_path = HERMES_HOME / ".env"
    env_content = (
        "# Hermes Offline — environment variables\n"
        "OLLAMA_FLASH_ATTENTION=1\n"
        "OLLAMA_KV_CACHE_TYPE=q8_0\n"
        "OLLAMA_NUM_PARALLEL=1\n"
        "OLLAMA_KEEP_ALIVE=0\n"
        "OLLAMA_MAX_LOADED_MODELS=1\n"
    )
    if not env_path.exists():
        env_path.write_text(env_content)
        console.print(f"[green]✓ Ollama env vars written to {env_path}[/green]")


if __name__ == "__main__":
    main()
